#!/bin/sh

## Copyright (C) 
## See the file COPYING for copying conditions.

if [ -x /usr/lib/i2p-torbrowser-sockets-workaround/i2pbrowser.sh ]; then
   . /usr/lib/i2p-torbrowser-sockets-workaround/i2pbrowser.sh
fi
